name: Build

on:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
      fail-fast: true
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install deps
        run: pip install -r requirements.txt
      - name: Discover version
        run: python magic_afm/make_version.py
      - name: Build with Pyinstaller
        run:  pyinstaller -y magic_gui_${RUNNER_OS::3}.spec
        shell: bash
      - name: Tidy dist
        if: startsWith( runner.os, 'mac')
        run: rm -rf dist/magic_gui
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: magic_gui-${{ matrix.os }}-build
          path: dist/
          if-no-files-found: error

